### ISSUE TITLE
(제안) 신규 줄서기 기능(긴급호출) 추가

### ISSUE THREAD

**Issue by minieetea** [totuworld/time-recorder-viewer#17]
1. 그냥 줄서는 것과 긴급으로 줄서는 기능이 있었으면 좋겠어요.
2. 줄서기 목록(띵동페이지)에는 긴급호출이 더 우선순위를 높게 받았으면 좋겠어요.

**Comment by totuworld** [comment]
기능을 쓰는 사람이 없어서 close
